# version: '3.7'  # obsolete

services:

  ubuntu:
    build:
      context: .
      dockerfile: Dockerfile
    image: my-ubuntu
    container_name: my-ubuntu-1

    hostname: myubuntu1

    restart: unless-stopped

    stdin_open: true
    tty: true

#    command: /sbin/init
#    command: /usr/bin/zsh
    command: /usr/bin/bash

    volumes:
      - ./_vol:/vol

    ports:
      - "10022:22"
