# version: '3.7'  # obsolete

services:

  sshd1:
    build:
      context: .
      dockerfile: Dockerfile
    image: sshd1_img

    container_name: sshd1_cont
    restart: unless-stopped

    hostname: sshd1host

#    stdin_open: true
#    tty: true

#    command: /sbin/init
#    command: /usr/bin/zsh
#    command: /usr/bin/bash
    command: /usr/sbin/sshd -D

    volumes:
      - ./_vol:/vol

    networks:
      - sshd1_net
    ports:
      - "10022:22"

networks:
  sshd1_net:
    driver: bridge
    enable_ipv6: false
