# version: '3.7'  # obsolete

services:

  ubuntu:
    build:
      context: .
      dockerfile: Dockerfile
    image: ubuntu1

    container_name: ubuntu1
    restart: unless-stopped

    hostname: ubuntu1

    stdin_open: true
    tty: true

#    command: /sbin/init
#    command: /usr/bin/zsh
    command: /usr/bin/bash

    volumes:
      - ./_vol:/vol
