# version: '3.7'  # obsolete

services:

  ubuntu1_svc:
    build:
      context: .
      dockerfile: Dockerfile
    image: ubuntu1_img

    container_name: ubuntu1_cont
    restart: unless-stopped

    hostname: ubuntu1

    stdin_open: true
    tty: true

    volumes:
      - ./_vol:/vol

    networks:
      - ubuntu1_net

#    command: /sbin/init
#    command: /usr/bin/zsh
    command: /usr/bin/bash

networks:
  ubuntu1_net:
    driver: bridge
    enable_ipv6: false
