# version: '3.7'  # obsolete

services:

  sshd:
    build:
      context: .
      dockerfile: Dockerfile
    image: my-sshd

    container_name: my-sshd-1
    restart: unless-stopped

    hostname: mysshd1

    stdin_open: true
    tty: true

#    command: /sbin/init
#    command: /usr/bin/zsh
#    command: /usr/bin/bash
    command: /usr/sbin/sshd -D

    volumes:
      - ./_vol:/vol

    ports:
      - "10022:22"
