# version: '3.7'  # obsolete

services:

  nodejs1_svc:
    build:
      context: .
      dockerfile: Dockerfile
    image: nodejs1_img

    container_name: nodejs1_cont
    restart: unless-stopped

    hostname: nodejs1host

#    stdin_open: true
#    tty: true

#    user: "ubuntu:ubuntu"

#    command: /sbin/init
#    command: /usr/bin/zsh
#    command: /usr/bin/bash
    command: sudo /usr/sbin/sshd -D

    volumes:
      - ./vol:/vol
      
#    network_mode: host
    networks:
      - nodejs1_net

    ports:
      - "10022:22"
      - "13000:3000"

networks:
  nodejs1_net:
    driver: bridge
    enable_ipv6: false
