# version: '3.7'  # obsolete

services:

  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    image: nodejs1

    container_name: nodejs1
    restart: unless-stopped

    hostname: nodejs1

    stdin_open: true
    tty: true

#    command: /sbin/init
#    command: /usr/bin/zsh
#    command: /usr/bin/bash
    command: /usr/sbin/sshd -D

    volumes:
      - ./_vol:/vol
      - ./work:/work

    ports:
      - "10022:22"
      - "13000:3000"
