# version: '3.7'  # obsolete

services:

  nodejs1_svc:
    build:
      context: .
      dockerfile: Dockerfile
    image: nodejs1_img

    container_name: nodejs1_cont
    restart: unless-stopped

    hostname: nodejs1host

    stdin_open: true
    tty: true

    volumes:
      - ./vol:/vol
      
    networks:
      - nodejs1_net

    ports:
      #- "10022:22"
      - "13000:3000"

    user: ytani
    command: /usr/bin/bash

    #command: /sbin/init
    #command: /usr/bin/zsh
    #command: sudo /usr/sbin/sshd -D

networks:
  nodejs1_net:
    driver: bridge
    enable_ipv6: false
