services:
  nginx80:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./data/conf:/etc/nginx/conf.d
      - ./data/logs:/var/log/nginx
      - ./data/html:/usr/share/nginx/html
    environment:
      - TZ=Asia/Tokyo
