# version: '3.7'  # obsolete

services:

  volta1_svc:
    build:
      context: .
      dockerfile: Dockerfile
    image: volta1_img

    container_name: volta1_cont
    restart: unless-stopped

    hostname: volta1host

    stdin_open: true
    tty: true

    volumes:
      - ./_vol:/vol

    networks:
      - volta1_net

    ports:
      - "13000:3000"

    user: ytani

#    command: /sbin/init
#    command: /usr/bin/zsh
    command: /usr/bin/bash

networks:
  volta1_net:
    driver: bridge
    enable_ipv6: false
